### ISSUE TITLE
tag v1.0.2?

### ISSUE THREAD

**Issue by shawnps** [google/subcommands#29]
It seems like [this commit](https://github.com/google/subcommands/commit/636abe8753b82e6eefa1beca9f46e49b470aa3d7) is not in a release - could you possibly tag `v1.0.2` with it?

**Comment by shawnps-sigsci** [comment]
@adjackura did you mean to tag `1.2.0`? I don't see a `1.1.0` so it seems like you may have skipped a minor version.

**Comment by luisdavim** [comment]
the problem is the missing `v` see #31
