### ISSUE TITLE
Tag versions correctly

### ISSUE THREAD

**Issue by luisdavim** [google/subcommands#31]
subcommands support Go modules, however some versions are tagged incorrectly, since the "v" prefix is missing.
For example, we have a release `v1.2.0` but the corresponding tag is `1.2.0`.

```
go get
go: github.com/google/subcommands@v1.2.0: reading github.com/google/subcommands/go.mod at revision v1.2.0: unknown revision v1.2.0
```

**Comment by adjackura** [comment]
This should be fixed now, thanks
