### ISSUE TITLE
Cancel propagate on Signals 

### ISSUE THREAD

**Issue by xmlking** [google/subcommands#34]
is this the recommended  way to   propagate `SIGTERM` type of signals to downstream components via context? or are there any other techniques? 
https://github.com/billchen1977/fuchsia/blob/master/tools/integration/cmd/fint/main.go#L41

**Comment by slewiskelly** [comment]
Yes, this is a fine way of handling them.

There's no real need to include `go.fuchsia.dev/fuchsia/tools/lib/command` as a dependency, you could copy the function body into your own tool. So for `SIGINT` and `SIGTERM` specifically:

```go
func main() {
	ctx, cancel := context.WithCancel(context.Background())
	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		defer signal.Stop(ch)
		select {
		case <-ctx.Done():
			return
		case <-ch:
			cancel()
		}
	}()

	os.Exit(int(subcommands.Execute(ctx)))
}
```

**Comment by thomasf** [comment]
since Go1.16 there is also `signal.NotifyContext` so you don't even have to copy that code.
