### ISSUE TITLE
go.sum not checked into repository

### ISSUE THREAD

**Issue by davidzech** [google/subcommands#35]
Per https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file `go.sum` should be checked into the repository.

The real world ramifications is that `go mod tidy` will silently break projects using `github.com/google/wire` via `go generate`

**Comment by slewiskelly** [comment]
There are no external dependencies so no `go.sum` file is generated.

**Comment by davidzech** [comment]
Yeah that makes sense. Also, making `wire` stick can be solved by explicitly importing subcommands.
